# Generated by Django 5.1.2 on 2024-10-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_analyzer', '0002_analyzedstyle_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedstyle',
            name='image_url',
        ),
        migrations.AddField(
            model_name='analyzedstyle',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
