name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Frontend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd Fashion-Sense-Rating
          git pull origin production
          cd frontend
          npm install
          npm run build
          # Use pm2 to manage the application
          pm2 stop frontend || true  # Stop the existing process if it exists
          pm2 start npm --name "frontend" -- run start  # Start the application in production mode
          pm2 save  # Save the process list
          EOF

  deploy_backend:
    runs-on: ubuntu-latest
    needs: deploy_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Backend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd Fashion-Sense-Rating
          git pull origin production
          cd backend
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py runserver
          EOF